name: Build APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Обновите до v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip python3-pip zlib1g-dev openjdk-17-jdk
          pip install buildozer

      - name: Build APK
        run: |
          buildozer -v android debug  # Уберите команды sed

      - name: Upload APK
        uses: actions/upload-artifact@v4  # Обновите до v4
        with:
          name: clicker-app
          path: bin/*.apk
